#!/usr/bin/env node
'use strict'

// Regenerates cheatsheet.html from assets/examples/data.json (same source of
// truth as examples.html / generate-examples.js), then uses Puppeteer to
// print that page to assets/kroki-cheatsheet.pdf and capture a small preview
// thumbnail for the homepage teaser.
//
// Puppeteer lives in scripts/cheatsheet/package.json, not the project's own
// package.json — it bundles a full Chromium download, and this script only
// runs occasionally, by hand, after editing assets/examples/data.json.
// `npm run generate-cheatsheet` installs it here (once; a no-op after that)
// before running this file, so the project's own `npm install` never pulls
// Chromium in.
//
// Each card's preview image is a live https://kroki.io/... request (the URL
// is built by ../kroki-url.js from the example's source + params, the same
// way examples.html does), not a locally cached SVG — that's the whole
// point of the cheat sheet, but it does mean a couple of diagram types that
// rely on inline SVG + @font-face (see the `inline` flag in data.json, e.g.
// Excalidraw) will render here with a fallback font: an <img> can't load an
// external font the way an inlined <svg> can.

const fs = require('fs')
const path = require('path')
const { buildUrl } = require('../kroki-url')

const root = path.join(__dirname, '..', '..')
const dataPath = path.join(root, 'assets', 'examples', 'data.json')
const cheatsheetPath = path.join(root, 'cheatsheet.html')
const indexPath = path.join(root, 'index.html')
const pdfPath = path.join(root, 'assets', 'kroki-cheatsheet.pdf')
const previewPath = path.join(root, 'assets', 'kroki-cheatsheet-preview.jpg')

const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'))

function renderFormatPills (formats) {
  return formats.map((f) => `<span class="diagram-support-format">${f}</span>`).join('')
}

function renderCard (type) {
  const example = type.examples[0]
  const { getPath } = buildUrl(type.type, 'svg', example.source, example.params)
  return `<div class="cheatsheet-card">
                <div class="cheatsheet-card-thumb"><img src="https://kroki.io/${getPath}" alt="${type.name} example" loading="lazy"/></div>
                <div class="cheatsheet-card-body">
                    <span class="cheatsheet-card-name">${type.name}</span>
                    <code class="cheatsheet-card-slug">${type.type}</code>
                    <div class="diagram-support-formats">${renderFormatPills(type.formats)}</div>
                </div>
            </div>`
}

function spliceBetweenMarkers (html, cardsHtml, filePath) {
  const startMarker = '<!-- CATALOG:START'
  const endMarker = '<!-- CATALOG:END -->'
  const start = html.indexOf(startMarker)
  const end = html.indexOf(endMarker) + endMarker.length
  if (start === -1 || end === -1) {
    throw new Error(`CATALOG:START / CATALOG:END markers not found in ${filePath}`)
  }
  const block = `<!-- CATALOG:START — generated by scripts/cheatsheet/generate.js from assets/examples/data.json. Do not edit by hand; edit the JSON and re-run the script instead. -->
        <div class="cheatsheet-grid">
            ${cardsHtml}
        </div>
        <!-- CATALOG:END -->`
  return html.slice(0, start) + block + html.slice(end)
}

function bustCacheQuery (html, assetPath, version) {
  const escaped = assetPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const pattern = new RegExp(`(["'])${escaped}(?:\\?v=[^"']*)?(["'])`, 'g')
  return html.replace(pattern, `$1${assetPath}?v=${version}$2`)
}

// networkidle0 only guarantees requests have settled, not that every
// live kroki.io thumbnail actually finished rendering — a cold backend for
// a less common diagram type (e.g. WireViz) can be slow enough to still be
// in flight, or to fail outright, leaving a blank thumbnail in the PDF.
// Force every thumbnail to load eagerly (ignoring `loading="lazy"`, which
// is only meant for real visitors scrolling the live site) and retry any
// that error out, giving kroki.io generous time to respond.
async function waitForCardImages (page, timeoutMs = 45000) {
  const failed = await page.evaluate(async (timeoutMs) => {
    const imgs = Array.from(document.querySelectorAll('.cheatsheet-card-thumb img'))
    imgs.forEach((img) => { img.loading = 'eager' })
    const loaded = await Promise.all(imgs.map((img) => new Promise((resolve) => {
      const deadline = Date.now() + timeoutMs
      const cleanup = () => {
        img.removeEventListener('load', onLoad)
        img.removeEventListener('error', onError)
      }
      const onLoad = () => { cleanup(); resolve(true) }
      const onError = () => {
        if (Date.now() >= deadline) { cleanup(); resolve(false); return }
        img.src = img.src
      }
      if (img.complete && img.naturalWidth > 0) { resolve(true); return }
      img.addEventListener('load', onLoad)
      img.addEventListener('error', onError)
      setTimeout(() => { cleanup(); resolve(img.complete && img.naturalWidth > 0) }, timeoutMs)
    })))
    return imgs.filter((_, i) => !loaded[i]).map((img) => img.alt)
  }, timeoutMs)
  if (failed.length) {
    console.warn(`Warning: ${failed.length} card image(s) did not load in time: ${failed.join(', ')}`)
  }
}

async function renderPdfAndPreview () {
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch()
  try {
    const page = await browser.newPage()
    await page.setViewport({ width: 1100, height: 800 })
    await page.goto(`file://${cheatsheetPath}`, { waitUntil: 'networkidle0', timeout: 120000 })
    await waitForCardImages(page)
    await page.pdf({
      path: pdfPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '70px', bottom: '50px', left: '30px', right: '30px' },
      displayHeaderFooter: true,
      headerTemplate: `<div style="font-size:9px; width:100%; text-align:center; color:#888; margin-top:20px;">Kroki Cheat Sheet — generated ${new Date().toISOString().slice(0, 10)}</div>`,
      footerTemplate: '<div style="font-size:9px; width:100%; text-align:center; color:#888;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>'
    })
    // page.pdf() renders with the "print" media type; switch back to
    // "screen" so the thumbnail matches what a visitor actually sees.
    await page.emulateMediaType('screen')
    await page.screenshot({ path: previewPath, type: 'jpeg', quality: 85, clip: { x: 0, y: 0, width: 1100, height: 700 } })
  } finally {
    await browser.close()
  }
}

async function main () {
  const cardsHtml = data.types.map(renderCard).join('\n            ')
  const cheatsheetHtml = spliceBetweenMarkers(fs.readFileSync(cheatsheetPath, 'utf8'), cardsHtml, 'cheatsheet.html')
  fs.writeFileSync(cheatsheetPath, cheatsheetHtml)
  console.log(`Generated ${data.types.length} type cards into cheatsheet.html`)

  console.log('Rendering PDF + preview with Puppeteer (this calls kroki.io live for every card)...')
  await renderPdfAndPreview()
  console.log(`Wrote ${path.relative(root, pdfPath)} and ${path.relative(root, previewPath)}`)

  const pdfVersion = Math.floor(fs.statSync(pdfPath).mtimeMs)
  const previewVersion = Math.floor(fs.statSync(previewPath).mtimeMs)

  fs.writeFileSync(cheatsheetPath, bustCacheQuery(fs.readFileSync(cheatsheetPath, 'utf8'), 'assets/kroki-cheatsheet.pdf', pdfVersion))
  fs.writeFileSync(indexPath, bustCacheQuery(fs.readFileSync(indexPath, 'utf8'), 'assets/kroki-cheatsheet-preview.jpg', previewVersion))

  console.log('Cache-busted the PDF and preview references in cheatsheet.html / index.html')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})